"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."

"preserve_hierarchy": true

"files": [
  {
    "source": "emulinker/src/main/i18n/messages.properties",
    "translation": "emulinker/src/main/i18n/messages_%two_letters_code%.properties"
  }
]
